### ISSUE TITLE
Daily Code Reviews - November 28th, 2019

### ISSUE THREAD

**Issue by zubiix** [zubiix/youtube-clone#4]
- Fix issue with video height
- Fix spacing with header icons
- Rename feature_branch to feature_youtube_clone
- Fix background with header icons
- Fix header on mobile devices
- Remove border on search box.
- Host on github pages
- Fix issues with font type and color.
- Add descriptive readme.

**Comment by Cyrus-Kiprop** [comment]
Resolved
